'use client';

import { Star, TrendingUp, DollarSign, Users, Brain, Target } from 'lucide-react';

export default function ProfileCard({ recommendation, userName }) {
  const getMatchColor = (percentage) => {
    if (percentage >= 80) return 'text-green-600';
    if (percentage >= 60) return 'text-yellow-600';
    return 'text-orange-600';
  };

  const getMatchBgColor = (percentage) => {
    if (percentage >= 80) return 'bg-green-100';
    if (percentage >= 60) return 'bg-yellow-100';
    return 'bg-orange-100';
  };

  return (
    <div 
      id="profile-card" 
      className="w-full max-w-xl mx-auto bg-white p-8 rounded-2xl shadow-2xl"
      style={{ 
        fontFamily: 'Inter, system-ui, sans-serif',
        lineHeight: '1.5',
        color: '#1f2937'
      }}
    >
      {/* Header */}
      <div className="text-center mb-8">
        <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <Star className="w-8 h-8 text-blue-600" />
        </div>
        <h1 className="text-2xl font-bold text-gray-900 mb-2" style={{ fontFamily: 'Poppins, system-ui, sans-serif' }}>
          {userName ? `${userName}'s Career Match` : 'Your Perfect Career Match'}
        </h1>
        <h2 className="text-xl font-semibold text-blue-600 mb-3" style={{ fontFamily: 'Poppins, system-ui, sans-serif' }}>
          {recommendation.primary.name}
        </h2>
        <p className="text-base text-gray-600 mb-4 leading-relaxed">
          {recommendation.primary.description}
        </p>
        
        {/* Match Percentage */}
        <div className="flex items-center justify-center gap-3 mb-6">
          <span className={`px-3 py-1 rounded-full text-sm font-semibold ${getMatchColor(recommendation.primary.match_percentage)}`}>
            {recommendation.primary.match_percentage}% Match
          </span>
          <span className="text-gray-500">•</span>
          <span className="text-gray-600 text-sm">{recommendation.primary.salary_range}</span>
        </div>
      </div>

      {/* Why This Path Fits - Main Content */}
      <div className="bg-blue-50 rounded-lg p-6 mb-6">
        <h3 className="text-lg font-semibold text-gray-800 mb-3 text-center" style={{ fontFamily: 'Poppins, system-ui, sans-serif' }}>
          Why This Path Fits You
        </h3>
        <p className="text-gray-700 text-center leading-relaxed text-sm">
          {recommendation.reasoning}
        </p>
      </div>

      {/* Key Skills - Simplified */}
      <div className="mb-6">
        <h3 className="text-base font-semibold text-gray-800 mb-3 text-center" style={{ fontFamily: 'Poppins, system-ui, sans-serif' }}>
          Key Skills
        </h3>
        <div className="flex flex-wrap gap-2 justify-center">
          {recommendation.primary.key_skills.slice(0, 4).map((skill, index) => (
            <span 
              key={index} 
              className="px-2 py-1 bg-blue-100 text-blue-700 rounded-full text-xs font-medium"
            >
              {skill}
            </span>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="text-center border-t border-gray-200 pt-4">
        <p className="text-sm text-gray-500 mb-1">
          Generated by PathFinder
        </p>
        <p className="text-xs text-gray-400">
          pathfinder.tech
        </p>
      </div>
    </div>
  );
}
